#redis:
#  host: 192.168.1.100
#  port: 6379
#  database: 0
#  timeout: 10000
#  password: 123456
#  pool:
#    maxTotal: 1024
#    maxActive: 1024
#    maxIdle: 100
#    minIdle: 50
#    maxWaitMillis: 20000 # 当池内没有返回对象时，最大等待时间
#    testOnBorrow: true
#    testWhileIdle: true
#    testOnReturn: true
#    minEvictableIdleTimeMillis: 500
#    softMinEvictableIdleTimeMillis: 1000
#    timeBetweenEvictionRunsMillis: 30000 # “空闲链接”检测线程，检测的周期，毫秒数。如果为负值，表示不运行“检测线程”。默认为-1.
#    numTestsPerEvictionRun: 100 # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3