spring:
    profiles:
      active: dev

redis:
  pool:
    maxTotal: 1024
    maxActive: 1024
    maxIdle: 64
    minIdle: 16
    maxWaitMillis: 20000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true
    minEvictableIdleTimeMillis: 500
    softMinEvictableIdleTimeMillis: 1000
    timeBetweenEvictionRunsMillis: 1000
    numTestsPerEvictionRun: 10